export const CASES = [
  {
    slug: 'stroitelstvo-korporativnyj-sajt',
    niche: 'Строительная компания',
    service: 'Многостраничный сайт',
    name: 'Сайт для строительной компании',
    year: '2023',
    task: 'Показать опыт, услуги, объекты и собрать заявки на консультацию.',
    work: 'Собрана структура услуг, портфолио объектов, формы заявки и SEO-основа под региональный спрос.',
    result: 'Компания получила понятную витрину работ и готовую основу для продвижения по строительным запросам.',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=1600',
    url: 'https://stroyinvest39.ru',
    serviceSlug: 'mnogostranyy',
    nicheSlug: 'stroitelnye-kompanii',
  },
  {
    slug: 'proizvodstvo-upakovka-sajta',
    niche: 'Производство оборудования',
    service: 'Упаковка под ключ',
    name: 'Упаковка промышленного проекта',
    year: '2023',
    task: 'Объяснить сложный продукт простым языком и усилить доверие к производству.',
    work: 'Пересобрана подача, добавлены блоки преимуществ, этапов, заявок и визуальная система.',
    result: 'Проект стал проще для восприятия и получил структуру для дальнейшего SEO-расширения.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=1600',
    url: '#',
    serviceSlug: 'upakovka',
    nicheSlug: 'stroitelnye-kompanii',
  },
  {
    slug: 'psiholog-lending',
    niche: 'Психологи',
    service: 'Лендинг',
    name: 'Лендинг для частного специалиста',
    year: '2024',
    task: 'Снять барьер первого обращения и объяснить формат консультаций.',
    work: 'Собраны блоки доверия, подхода, стоимости, FAQ и быстрых способов связи.',
    result: 'Посадочная стала понятной для клиента и готовой к запуску рекламного трафика.',
    image: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&q=80&w=1600',
    url: '#',
    serviceSlug: 'lending',
    nicheSlug: 'psihologi',
  },
]

export type CaseItem = (typeof CASES)[number]
